const cupcakes = [
    {
      _id: '1',
      name: 'Vanilla Cupcake',
      image: '/Cupcakes/VanillaCupcake.jpg',
      description:
        'Soft and fluffy vanilla cupcake with vanilla Cream Icing and sprinkles',
      brand: 'Apple',
      category: 'Cupcakes',
      price: 1.70,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'Red Velvet Cupcake',
      image: '/Cupcakes/RedVelvetCupcake.jpg',
      description:
        'Red Velvet recipe with cream icing and Red Velvet Sprinkles',
      brand: 'Apple',
      category: 'Cupcakes',
      price: 1.70,
      countInStock: 7,
      rating: 4.0,
      numReviews: 8,
    },
    {
      _id: '3',
      name: 'Chocolate & Oreo Cupcake',
      image: '/Cupcakes/OreoCupcakes.jpg',
      description:
        'Moist Hershey chocolate recipe with oreo cream icing and an oreo',
      brand: 'Cannon',
      category: 'Cupcakes',
      price: 2.20,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: '4',
      name: 'RedVelvet Strawberry & Cream Cupcake',
      image: '/Cupcakes/StrawberryCupcake.jpg',
      description:
        'Best seller strawberry cupcake . Can be a plain vanilla base with strawberry goo or Red Velvet for a red effect',
      brand: 'Sony',
      category: 'Electronics',
      price: 2.20,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'Lemon Cupcake',
      image: '/Cupcakes/LemonCupcake.jpg',
      description:
        'Lemony cupcake filled with lemon curd topped with cream icing and lemon piece',
      brand: 'Logitech',
      category: 'Cupcakes',
      price: 2.20,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: '6',
      name: 'Double Chocolate Cupcake',
      image: '/Cupcakes/DoubleChocolateCupcake.jpg',
      description:
        'Moist Hershey Chocolate recipe for the cupcake with chocolate icing topped with chocolate sprinkles',
      brand: 'Amazon',
      category: 'Cupcakes',
      price: 2.00,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
    },
    {
        _id: '7',
        name: 'Raspberry Cupcake',
        image: '/Cupcakes/RaspberryCupcake.jpg',
        description:
          'Vanilla cupcake with real raspberries inside topped with raspberry flavour icing cream and a rasberry',
        brand: 'Amazon',
        category: 'Cupcakes',
        price: 2.20,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '8',
        name: 'Caramel Cupcake',
        image: '/Cupcakes/CaramelCupcakes.jpg',
        description:
        'This is a brown sugar cupcake topped with cream icing and caramel drizzle',
        brand: 'Amazon',
        category: 'Cupcakes',
        price: 2.00,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '9',
        name: 'Blueberry Cupcake',
        image: '/Cupcakes/BlueberryCupcake.jpg',
        description:
          'This is a Blueberry cupcake with real fruits inside and purple icing topped with berries',
        brand: 'Amazon',
        category: 'Cupcakes',
        price: 2.20,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '10',
        name: 'Speculoos Cupcake',
        image: '/Cupcakes/SpeculoosCupcake.jpg',
        description:
          'Caramel cupcake with speculoos flavored icing topped with speculoos biscuit',
        brand: 'Amazon',
        category: 'Cupcakes',
        price: 2.00,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '11',
        name: 'Cuberdon Cupcake',
        image: 'Cupcakes/cupcake-1.jpeg',
        description:
          'Raspberry cupcake with raspberry icing topped with Sweet Red Cuberdon',
        brand: 'Amazon',
        category: 'Cupcakes',
        price: 2.00,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '12',
        name: 'Chocolate Mokka Cupcake',
        image: '/Cupcakes/MokaCupcake.jpg',
        description:
          'Like the taste of coffee in a cupcake ? then this cupcake is for you! Moist Chocolate cupcake with mokka buttercream ',
        brand: 'Amazon',
        category: 'Cupcakes',
        price: 2.00,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '13',
        name: 'Emoji Cupcake',
        image: '/Cupcakes/EmojiCupcake.jpg',
        description:
          'Moist Vanilla cupcake topped with Emoji Fondant to impress your guest',
        brand: 'Amazon',
        category: 'Cupcakes',
        price: 2.00,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '14',
        name: 'Rafaelo Cupcake',
        image: '/Cupcakes/RaffaelloCupcakes.jpg',
        description:
          'Taste our moist coconut cupcake topped with icing,coconut flakes and a Raffaello',
        brand: 'Amazon',
        category: 'Cupcakes',
        price: 2.00,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '15',
        name: 'PeanutButter Banana Cupcake',
        image: '/Cupcakes/PeanutButterBananaCupcake.jpg',
        description:
          'Sweet peanut butter cupcake topped with Banana icing and Caramel pieces',
        brand: 'SweetAmbition',
        category: 'Cupcakes',
        price: 2.20,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '16',
        name: 'Carrot Cupcake',
        image: '/Cupcakes/CarrotCupcakes.jpg',
        description:
          'Carrot cake base with cream cheese frosting',
        brand: 'Amazon',
        category: 'Cupcakes',
        price: 1.70,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '17',
        name: 'Mango Cupcake',
        image: '/Cupcakes/TropicalMangoCupcake.jpg',
        description:
          'Delicious Vanilla Cupcake filled with mango puree topped with mango icing',
        brand: 'Amazon',
        category: 'Cupcakes',
        price: 2.20,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '18',
        name: 'Ube Macapuno Cupcake',
        image: '/Cupcakes/UbeMacapunoCupcake.jpg',
        description:
          'Taste our filipino flavoured ube cupcake with ube icing ,topped with Coconut strings',
        category: 'Cupcakes',
        price: 2.00,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
      {
        _id: '2',
        name: 'Cupcakes Fruits Rouges',
        image: '/images/FruitRougesCupcake.png',
        description:
          'Vanilla Sponge cupcake with vanilla cream icing topped with fresh berries ',
        brand: 'Apple',
        category: 'Cupcakes',
        price: 2.5,
        countInStock: 7,
        rating: 4.0,
        numReviews: 8,
      },
    ]
  
    export default cupcakes
    